apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: roboshop
spec:
  serviceAccount: secret-reader
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "10000"]